# Generated by Django 6.0 on 2026-01-21 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comerciojusto', '0004_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificacao',
            name='arquivo_certificado',
            field=models.FileField(blank=True, null=True, upload_to='certificacoes/'),
        ),
        migrations.AddField(
            model_name='certificacao',
            name='parecer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificacao',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificacoes', to='comerciojusto.perfil'),
        ),
        migrations.AlterField(
            model_name='certificacao',
            name='administrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comerciojusto.administrador'),
        ),
        migrations.AlterField(
            model_name='certificacao',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comerciojusto.produto'),
        ),
        migrations.AlterField(
            model_name='certificacao',
            name='status',
            field=models.CharField(choices=[('nao_disponivel', 'Não Disponível'), ('enviado_analise', 'Enviado para Análise'), ('aprovada', 'Aprovada'), ('reprovada', 'Reprovada')], default='enviado_analise', max_length=20),
        ),
    ]
