# Generated by Django 6.0 on 2026-01-24 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comerciojusto', '0006_itempedido_pedido_itempedido_pedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'verbose_name': 'Administrador', 'verbose_name_plural': 'Administradores'},
        ),
        migrations.AlterModelOptions(
            name='anunciomarketplace',
            options={'verbose_name': 'Anúncio Marketplace', 'verbose_name_plural': 'Anúncios Marketplace'},
        ),
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['-data_avaliacao'], 'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterModelOptions(
            name='carrinho',
            options={'verbose_name': 'Carrinho', 'verbose_name_plural': 'Carrinhos'},
        ),
        migrations.AlterModelOptions(
            name='certificacao',
            options={'verbose_name': 'Certificação', 'verbose_name_plural': 'Certificações'},
        ),
        migrations.AlterModelOptions(
            name='documento',
            options={'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='itempedido',
            options={'verbose_name': 'Item do Pedido', 'verbose_name_plural': 'Itens dos Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='mensagem',
            options={'verbose_name': 'Mensagem', 'verbose_name_plural': 'Mensagens'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-data_pedido'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['-destaque', '-vendas'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='produtor',
            options={'verbose_name': 'Produtor', 'verbose_name_plural': 'Produtores'},
        ),
        migrations.AlterModelOptions(
            name='publicacao',
            options={'ordering': ['-data_publicacao'], 'verbose_name': 'Publicação', 'verbose_name_plural': 'Publicações'},
        ),
        migrations.AddField(
            model_name='perfil',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='certificacao',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificacoes', to='comerciojusto.produto'),
        ),
    ]
