# Generated by Django 6.0 on 2026-01-25 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comerciojusto', '0007_alter_administrador_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='produtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comerciojusto.produtor'),
        ),
    ]
