# Generated by Django 6.0 on 2026-01-25 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comerciojusto', '0008_alter_produto_produtor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='capa',
        ),
    ]
