# Generated by Django 6.0 on 2026-01-25 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comerciojusto', '0009_remove_perfil_capa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publicacao',
        ),
    ]
